# Test And Deploy
# ---------------
name: Test Functions
on:
  push:
      branches:
        - master
jobs:
   test-functions:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4.1.1
         
          # Install .NET 8.0 SDK
         - name: Install .NET 8.0 SDK
           uses: actions/setup-dotnet@v4.0.0
           with: 
            dotnet-version: '8.0'
          # Install dependencies
         - name: Install dependencies
           run: dotnet restore
          # Build
         - name: Build
           run: dotnet build --no-restore
          # Test Functions in the project - Run XUnit-Tests
         - name: Test
           run: dotnet test --no-restore --verbosity normal
          # Creating the publish file
         - name: Create publish files
           run: dotnet publish --configuration Release --output ./publish
           # Deploy to Azure Web App
         - name: Deploy to Azure Web App
           uses: azure/webapps-deploy@v3.0.0
           with:
            app-name: 'TestDrivenHotel'
            publish-profile: ${{ secrets.TESTDRIVENHOTEL_WEBB_APP_KEY }}
            package: './publish'
  