# Test And Deploy
# ---------------
name: Test Functions
on:
  push:
    branches:
      - master
jobs:
   test-functions:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4.1.1
 
        
  